language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - 2.3.0
  - ruby-head
  - jruby
  - jruby-head

sudo: false

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
